### ISSUE TITLE
ufw and systemctl command is not working inside docker container

### ISSUE THREAD

**Issue by naveenrpp2017** [docker/containerd-packaging#343] opened 2024-03-08 09:06 UTC
Hello team,

I have to start some service using systemctl using dockerfile.  dockerfile contains ufw allow command that is also failing

ufw error:
56.90 WARN: initcaps
56.90 [Errno 2] iptables v1.8.4 (legacy): can't initialize iptables table `filter': Permission denied (you must be root)
56.90 Perhaps iptables or your kernel needs to be upgraded.

systemctl error: ( I dont want to use service command)
57.16 System has  not been booted with systemd as init system (PID 1). Can't operate.
57.16 Failed to connect to bus: Host is down
57.16 System has not been booted with systemd as init system (PID 1). Can't operate.
57.16 Failed to connect to bus: Host is down

My requirement:
I can only run docker build from my side and i have to use ufw and systemctl 
with docker run i know about --privileged flag but as i have mentioned i can only access to dockerfile and run dockerbuild

**Comment by thaJeztah** [comment] 2024-03-13 11:39
I don't think this issue tracker is the right location for this question; for questions related to build, you could open a discussion in https://github.com/moby/buildkit/discussions, but build (by design) does not allow for privileged containers (a container with `--privileged` does not "contain"; effectively providing full root access to the host, which means the build won't be in an isolated environment).

Making iptables changes as part of a build step also unlikely will do what you'd expect, as these changes would only be effective (at most) in the step running the command, and not in follow-up steps (nor would they be persisted in the image you're building), so if you decide to start a discussion there, it may be good to describe what you're trying to do and what you're trying to achieve (instead of only the issue / error encountered).


I'll close this ticket because of the above

**Closed by thaJeztah** 2024-03-13 11:39 UTC
